services:
  - type: web
    name: flask-socketio-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: PORT
        value: 10000
